### ISSUE TITLE
Draggable and Multiple Text isn't supported

### ISSUE THREAD

**Issue by UtkarshA135** [mehdizarepour/text_editor#1]
This pluggin currently doesn't support Draggable text 
also only text is supported

**Comment by mehdizarepour** [comment]
Hi @UtkarshA135, Thank you for opening this issue.
What do you mean by Draggable and Multiple Text? Can you explain a little more?

**Comment by UtkarshA135** [comment]
Hi !! IActually I was working on a business card feature for my app and I used your pluggin for text editing 
The pluggin is great but found a flaw that it did n't support draggable text over image , I mean we can't Position it anywhere we want , also multipe texts aren't supported  .
I'm attaching a drive link just see , you will understand what I mean
Actually I have solved this issue .
Can I make a pull request ?
[https://drive.google.com/file/d/1X0nwDF62UHkOLGUnXLJOD9TdoHDSie3n/view?usp=drivesdk](url)

**Comment by mehdizarepour** [comment]
> it did n't support draggable text over image

@UtkarshA135 My dear friend, TextEditor's not responsible for transforming a text widget, It's just for editing your text style.
If you need to move your text widget on the screen, you can use `Transform` widget. I've prepared a sample, I hope It can help you:

```dart
Scaffold(
  resizeToAvoidBottomInset: false,
  body: SafeArea(
    child: Center(
      child: Transform(
        transform: _matrix,
        child: GestureDetector(
          onTap: () => _tapHandler(_text, _textStyle, _textAlign), // Open TextEditor in a showGeneralDialog
          onScaleStart: (ScaleStartDetails scaleStartDetails) {
            setState(() {
              _matrix4transform = Matrix4Transform.from(_matrix);

              _translateDx = scaleStartDetails.focalPoint.dx;
              _translateDy = scaleStartDetails.focalPoint.dy;
            });
          },
          onScaleUpdate: (ScaleUpdateDetails scaleUpdateDetails) {
            setState(() {
              _matrix = _matrix4transform
                  .translate(
                    x: scaleUpdateDetails.focalPoint.dx - _translateDx,
                    y: scaleUpdateDetails.focalPoint.dy - _translateDy,
                  )
                  .matrix4;
            });
          },
          child: Text(
            _text,
            style: _textStyle,
            textAlign: _textAlign,
          ),
        ),
      ),
    ),
  ),
)
```
![sample](https://user-images.githubusercontent.com/8446770/98903378-b693cd00-24cc-11eb-8937-3116fd8fbd5b.gif)

If you have any questions please feel free to ask.

Thanks, Mehdi

**Comment by UtkarshA135** [comment]
Yup this helps :)
