### ISSUE TITLE
Change "DONE" button text

### ISSUE THREAD

**Issue by 88hitman** [mehdizarepour/text_editor#2]
Hi ! Firstly, thanks a lot for this plugin, its awesome

Then, I would like to be able to change the "DONE" button text by a text of my choice. 
Can you please take a look to provide us a way to change it ? Thank you

**Comment by mehdizarepour** [comment]
Hi @88hitman, Thank you for opening this issue.
Actually, I was thinking about it! I was planning to add a decoration property to make customizable every text or icon.

Something like this:

```dart
TextEditor(
  fonts: fonts,
  text: text,
  textStyle: textStyle,
  textAlingment: textAlign,
  decoration: EditorDecoration(
    doneButton: Text('Close'), // Or Icon(Icons.close)
    alignment: AlignmentDecoration(
      right: ...,
      left: ...,
      center: ...,
    ),
    ...
  )
  onEditCompleted: (style, align, text) {
    setState(() {
      _text = text;
      _textStyle = style;
      _textAlign = align;
    });
  },
)
```

**Comment by 88hitman** [comment]
This is exactly what I was looking for:)

By the way, do you plan to let us choose a list of colors in this EditorDecoration widget ? 
Thks !

**Comment by mehdizarepour** [comment]
Do you mean the colors of the palette?

**Comment by 88hitman** [comment]
Yes exactly, I saw that you hard coded color values in your ColorPalette class. Is it final ?

**Comment by mehdizarepour** [comment]
No, It's not final.
You would be able to change those colors by `EditorDecoration` too.

**Comment by 88hitman** [comment]
Glad to hear it, thank you

**Comment by mehdizarepour** [comment]
Hi @88hitman 
I've decided not to add the palette's color property to `decoration`. Instead, I added an optional property named `paletteColors` to `TextEditor` class, you can pass your custom colors to `paletteColors` property.

```diff
TextEditor(
  fonts: fonts,
  text: text,
  textStyle: textStyle,
  textAlingment: textAlign,
+  paletteColors: [
+    Colors.black,
+    Colors.white,
+    Colors.blue,
+    Colors.red,
+    Colors.green,
+    Colors.yellow,
+    Colors.pink,
+    Colors.cyanAccent,
+  ],
+  decoration: EditorDecoration(
+    doneButton: Icon(Icons.close, color: Colors.white),
+    fontFamily: Icon(Icons.title, color: Colors.white),
+    colorPalette: Icon(Icons.palette, color: Colors.white),
+    alignment: AlignmentDecoration(
+      left: Text(
+        'left',
+        style: TextStyle(color: Colors.white),
+      ),
+      center: Text(
+        'center',
+        style: TextStyle(color: Colors.white),
+      ),
+      right: Text(
+        'right',
+        style: TextStyle(color: Colors.white),
+      ),
+    ),
+  ),
),
```

I'm closing this issue, feel free to reopen it if you have any problem.
thanks.
